### ISSUE TITLE
csv list index out of range

### ISSUE THREAD

**Issue by cgseitz** [DrewBarratt/MD_Network_analysis#1]
Hello,

I am trying to follow the "HRPa_Ca_network_analysis" jupyter notebook provided along with the recent preprint "N-linked glycosylation increases horse radish peroxidase rigidity leading to enhanced activity and stability" and apply it to my own system. This line in the jupyter notebook is giving me issues:

```glycos_restack_2 = glycos_2.stack().reset_index()```

When I run it, I get an error saying that the list index is out of range. I'm wondering if the csv files I'm importing into the jupyter notebook are formatted incorrectly. Do you have an example csv that works in the jupyter notebook that you could provide? Thanks!

Best,
Christian

**Comment by DrewBarratt** [comment]
Hi @cgseitz , 

Truth be told, the conversion of the GROMACS MDmat distance matrix to a usable CSV for the notebook was quite tricky. It might be the case of needing to modify the index in your CSV or making sure that you’re using the right delimiter when converting from the standard output? Im also assuming that the format and indexing of both CSVs are the same? 

Please find attached an example of one of the CSV files that I used for this analysis. 

Also, I’ll update the code with comments later today to clarify whats going on. 

Feel free to email me your CSV through my academic email address and I can let you know if I can see anything ovbious - barrattah@cardiff.ac.uk

Hope this helps! 

Cofion/Regards, 

Drew

[HRP-glycos.csv](https://github.com/DrewBarratt/MD_Network_analysis/files/10919635/HRP-glycos.csv)

**Comment by cgseitz** [comment]
Hi Drew,

I have looked over the csv you attached, but I didn't immediately notice any differences between yours and my csv files. I have sent you an email. Thanks!

Best,
Christian
